@startuml
skinparam linetype polyline
hide circle
hide stereotype
hide methods

package "Bundle" {
  class "  RequestGroup  " as RG #cfc{  }

    class "  Patient  " as P #cff{
  }
P .u. RG 
P .r. T 
P .r. CD 


  class "  Task  " as T #ffd{

    }

RG ".action" o-- T 

  class " Condition " as CD #fdd{  
    
  }

T ".input" o-d- CD
RG -r[hidden]- CD
}

legend
Response is a Bundle containing
* a RequestGroup
* 0..N Tasks as a request
** to propose a set of diagnoses (Conditions) to consider

each Task is an option in RequestGroup
Tasks indicate "Please consider this diagnoseis"
endlegend

@enduml