@startuml
skinparam linetype polyline
hide circle
hide stereotype

package "Bundle" {
  class "  RequestGroup  " as RG #cfc{
  }

  
  class "  Patient  " as P #cff{
  }
P .r. RG
P .r. T 

  class "  ServiceRequest  " as T #ffe{
  }

RG ".action" o-- T 


}
legend
Response is a Bundle containing
* a RequestGroup
* 0..N Requests (ServiceRequests)

each ServiceRequest is an option in
the requestGroup, and has scoring
endlegend
@enduml