@startuml
!pragma teoz true
Title PSS Functional data exchange - antibiotics
hide footbox


group #def Service 2 - Given indications, query data to collect
        Activate EPD
        EPD -> PSS : \n**POST /PlanDefinition/GetDataToCollect/$apply**\n Payload:\n        subject=Y\n        data=Bundle
        Activate PSS
        note right of PSS
See 1. below
        end note

        PSS -> EPD: 1. Propose data to collect
        note right of PSS
See 2. below
        end note
        deactivate PSS
        |||
end
...
group #fed Service 3 - Given the requested data, request recommended medications
        EPD -> PSS : \n**POST /PlanDefinition/GetRecommendations/$apply**\n Payload:\n        subject=Y\n        data=Bundle
        note right of PSS
See 3. below
        end note
        activate PSS
        PSS -> EPD: 2. Bundle with RequestGroup with options
        note right of PSS
See 4. below
        end note
        deactivate PSS
        |||

end
@enduml
