@startuml
!pragma teoz true
Title PSS Functional data exchange
hide footbox

group #edf PSS-0 - Confirm consent
        EPD -> PSS : \n**POST /Consent**
        activate PSS
        note right of EPD
|_ HCP-ID
|_ datetime
|_ terms&conditions
  |_ url
  |_ text
  |_ version
  |_ options
        end note
        deactivate EPD
        deactivate PSS
end
|||
|||
group #DFE PSS-1 - Given existing data, query the structured list of applicable indications
        activate EPD
        EPD -> PSS : \n**POST /PlanDefinition/GetDiagnoses/$apply**\n Payload:\n        subject=PSSPatient\n        data=PSSRequestBundle
        & PSS -> QSI 
        & PSS -[hidden]-> QSI : "                                      "
        'PSS -> QSI : GET /indictions

        activate PSS
        activate QSI
        QSI -> PSS 
        & PSS -> EPD: Propose Indications \nPayload:\n        subject=PSSPatient\n        data=PSSResponseBundle
        deactivate PSS
        deactivate QSI
        |||
end

...
group #fed PSS-3 - Given some data (+ a procedure), request recommended procedures
        EPD -> PSS : \n**POST /PlanDefinition/GetRecommendations/$apply**\n Payload:\n        subject=Y\n        data=Bundle
        & PSS --> QSI 
        & PSS -[hidden]-> QSI : "                                      "

        activate PSS
        activate QSI
        QSI --> PSS 
        & PSS -> EPD: Reponse\nPayload:\n        subject=PSSPatient\n        data=PSSResponseBundle
        deactivate PSS
        deactivate QSI
        |||

end
...
group #efd PSS-4 - Give feedback
        EPD -> PSS : \n**POST /PlanDefinition/$feedback**\n Payload:\n        pss-id={exchangeId}\n        feedback-resource=Task or Bundle
        note left of PSS
|_ Task (FeedbackTask)
  or
|_ Bundle (PSSFeedbackBundle)
  |_ Task (FeedbackTask)
  |_ ServiceRequest (alternative)
        end note
        deactivate EPD
        activate PSS
        & PSS -[hidden]-> QSI : "                                      "
        deactivate PSS
        |||

end

...
...

group #fde PSS-5 - Consult prior result
        EPD -> PSS : \n**GET /Bundle/{PSS-ID}&_tag=recommendation**
        & PSS -[hidden]-> QSI : "                                      "
'        activate EPD
end
...

group #dfe PSS-6 - Consult feedback
'        ADM -> PSS : \n**GET /Bundle?identifier={PSS-ID}**\n**&_profile=.../PSSFeedbackBundle**
         -> PSS : \n**GET /Bundle?identifier={PSS-ID}&_tag=feedback**
        activate PSS
        <- PSS   : Bundle (PSSFeedbackBundle)
        & PSS -[hidden]-> QSI : "                                      "
        deactivate PSS
        |||

'        activate EPD
end



@enduml

