# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource.                     │
# │  For a list of supported properties, see:                                                      │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# │  SUSHI will use id as both id and packageId in the IG unless a                                 │
# │  specific packageId is also provided in this file.                                             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯


id: hl7.fhir.be.pss
canonical: https://www.ehealth.fgov.be/standards/fhir/pss
# url: http://example.com/fhir/example/ImplementationGuide/my-ig
name: PrescriptionSearchSupport
title: "Prescription Search Support"
description: Example IG exercises many of the fields in a SUSHI configuration.
status: draft
license: CC0-1.0
date: 2024-04-26
version: 1.0.0

# Although fhirVersions is 0..* in the ImplementationGuide resource
# it can be a single item OR and array here, but the current tooling 
# only supports one FHIR version per Implementation Guide
fhirVersion: 4.0.1

# The following two lines correspond to items that used to be in
# ig.ini but were moved to IG.definition.parameter. For
# consistency within this file, the names are represented using
# camelcase, but if authors use the formal parameter names, SUSHI
# will recognize them as well. In either case, they'll be copied
# to the IG JSON using the formal names.
copyrightYear: 2021+
releaseLabel: STU1

# The publisher can be a single item or a list, each with a name and
# optional url and/or email. The first publisher's name will be used
# as IG.publisher.  The contact details and/or additional publishers
# will be translated into IG.contact values.
publisher:
  name: HL7 Belgium 
  url: https://www.hl7belgium.org
  email: hl7belgium@hl7belgium.org

# ContactDetail is required by the template.
contact:
  - name: Message Structure eHealth
    telecom:
      - system: email
        value: message-structure@ehealth.fgov.be
        use: work

# The jurisdiction can be a single item or a list. The FHIR Shorthand
# code syntax can be used here.

#jurisdiction: urn:iso:std:iso:3166#US "United States of America"
jurisdiction: urn:iso:std:iso:3166#BE "Belgium"


# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for `uri` and `version`.
dependencies:
  hl7.fhir.uv.cpg:
    id: cpg
    uri: https://hl7.org/fhir/uv/cpg/ImplementationGuide/hl7.fhir.uv.cpg
    version: 2.0.0


# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs.
#global:
#  Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#  Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile

# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#resources:
#  Patient/my-example-patient:
#    name: My Example Patient
#    description: An example Patient
#    exampleBoolean: true
#  Patient/bad-example: omit

# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds.
groups:
  LogicalModels:
    name: Logical Models
    description: Data Models representing the data structures and requirements for interoperability.
    resources:
      - StructureDefinition/PSSRequest
      - StructureDefinition/PSSResponse

  PlanDefinitions:
    name: PlanDefinitions (services)
    description: PlanDefinitions defining the service endpoints for using the PSS. These have the inputs and outputs represented by the profiles
    resources:
      - PlanDefinition/GetDiagnoses
      - PlanDefinition/GetDataToCollect
      - PlanDefinition/GetRecommendations

  Profiles: 
    name: Resource Profiles
    description: These define constraints on FHIR resources for systems conforming to this implementation guide
    resources:
      - StructureDefinition/PSSRequestBundle
      - StructureDefinition/PSSResponseBundle
      - StructureDefinition/PSSDataAcquisitionForm
      - StructureDefinition/PSSResponseRequestGroup
      - StructureDefinition/PSSResponseMedicationRequest
      - StructureDefinition/PSSResponseServiceRequest

  Extensions: 
    name: Extensions
    description: These define additional elements that can be exchanged with the respective FHIR resources
    resources:
      - StructureDefinition/CodeValueSet
      - StructureDefinition/PSSStructuredRating
      - StructureDefinition/PSSRelevantAge
      - StructureDefinition/PSSCodedRating


  Antimicrobiology:
    name: Examples - Antimicrobiology
    description: Antimicrobiology PSS resource examples
    resources:
      - Patient/patient-a
      - Bundle/getdatatocollect-a-data
      - vulvovaginitis
      - AllergyIntolerance/allergy-to-sulfonamide
      - MedicationRequest/proposal-clindamycin

      - Bundle/getdatatocollect-a-return
      - RequestGroup/getdatatocollect-a-return-group
      - Task/collect-information-a
      - Questionnaire/q-collect-information-a
      - ValueSet/condition-valueset
      - ValueSet/PregnancyCodes

      - Bundle/getrecommendations-a-data
      - QuestionnaireResponse/qresponse-v

      - Bundle/getrecommendations-a-return
      - RequestGroup/getrecommendations-a-return-group
      - CommunicationRequest/ab-advice
      - MedicationRequest/metronidazol
      - MedicationRequest/clindamycin
      - MedicationRequest/fluconazol
      - MedicationRequest/miconazol

  Radiology:
    name: Examples - Radiology
    description: Radiology PSS resource examples
    resources: 
      - Patient/patient-r
      - Bundle/radiology-getdiagnoses
      - Observation/ataxia
      - Bundle/radiology-getdiagnoses-return
      - RequestGroup/Inline-Instance-for-radiology-getdiagnoses-return
      - Task/propose-stroke
      - Condition/proposed-diagnosis-stroke
      - Task/propose-infection
      - Condition/proposed-diagnosis-infection
      - Task/propose-head-trauma
      - Condition/proposed-diagnosis-head-trauma
      - Task/propose-slow-progression-ataxia
      - Condition/proposed-diagnosis-slow-progression-ataxia
      - Task/propose-post-trauma-ataxia
      - Condition/proposed-diagnosis-post-trauma-ataxia

      - Bundle/getrecommendations-data3
      - Condition/proposed-diagnosis-head-trauma-v2
      - ServiceRequest/ct-head-iv-contrast-v2

      - Bundle/getrecommendations-r-return
      - RequestGroup/getrecommendations-r-return-1
      - ServiceRequest/ct-head-iv-contrast
      - ServiceRequest/ct-head-with-or-without-contrast
      - ServiceRequest/mr-head-without-contrast
      
#      - ServiceRequest/ct-head-iv-contrast


# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
pages:
  index.xml:
    title: Home
  functional-overview.md:
    title: "Functional Overview"
    radiology.md:
      title: "Radiology"
    antimicrobiology.md:
      title: "Antimicrobiology"
  changes.xml:
  downloads.xml:
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId

# The menu property will be used to generate the input/menu.xml file.
# The menu is represented as a simple structure where the YAML key
# is the menu item name and the value is the URL. The IG publisher
# currently only supports one level deep on sub-menus.
# To provide a custom menu.xml file, do not include this property and
# include a `menu.xml` file in input/includes.
menu:
  Home: index.html
#  Guidance: guidance.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Changes: changes.html
#  History: ../history.html

# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array. For a
# partial list of allowed parameters see:
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
#parameters:
#  excludettl: true
#  validation: [allow-any-extensions, no-broken-links]

# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The default value for this property is false.
FSHOnly: false

# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. Default is true.
#applyExtensionMetadataToRoot: false
