# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource.                     │
# │  For a list of supported properties, see:                                                      │
# │  https://fshschool.org/docs/sushi/configuration/#full-configuration                            │
# │  SUSHI will use id as both id and packageId in the IG unless a                                 │
# │  specific packageId is also provided in this file.                                             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯


id: hl7.fhir.be.pss
canonical: https://www.ehealth.fgov.be/standards/fhir/pss
# url: http://example.com/fhir/example/ImplementationGuide/my-ig
name: PrescriptionSearchSupport
title: "Prescription Search Support"
description: Example IG exercises many of the fields in a SUSHI configuration.
status: active
license: CC0-1.0
date: 2024-04-26
version: 1.0.0

# Although fhirVersions is 0..* in the ImplementationGuide resource
# it can be a single item OR and array here, but the current tooling 
# only supports one FHIR version per Implementation Guide
fhirVersion: 4.0.1

# The following two lines correspond to items that used to be in
# ig.ini but were moved to IG.definition.parameter. For
# consistency within this file, the names are represented using
# camelcase, but if authors use the formal parameter names, SUSHI
# will recognize them as well. In either case, they'll be copied
# to the IG JSON using the formal names.
copyrightYear: 2021+
releaseLabel: STU1

# The publisher can be a single item or a list, each with a name and
# optional url and/or email. The first publisher's name will be used
# as IG.publisher.  The contact details and/or additional publishers
# will be translated into IG.contact values.
publisher:
  name: eHealth Platform Belgium 
  url: https://www.ehealth.fgov.be/standards/fhir/
  email: support@be-ehealth-standards.atlassian.net

# ContactDetail is required by the template.
contact:
  - name: Message Structure eHealth
    telecom:
      - system: email
        value: support@be-ehealth-standards.atlassian.net
        use: work

# The jurisdiction can be a single item or a list. The FHIR Shorthand
# code syntax can be used here.

#jurisdiction: urn:iso:std:iso:3166#US "United States of America"
jurisdiction: urn:iso:std:iso:3166#BE "Belgium"


# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for `uri` and `version`.
dependencies:
  hl7.fhir.uv.cpg:
    id: cpg
    version: 2.0.0


# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs.
#global:
#  Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#  Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile

# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#resources:
#  Patient/my-example-patient:
#    name: My Example Patient
#    description: An example Patient
#    exampleBoolean: true
#  Patient/bad-example: omit

# Groups can control certain aspects of the IG generation.  The IG
# documentation recommends that authors use the default groups that
# are provided by the templating framework, but if authors want to
# use their own instead, they can use the mechanism below.  This will
# create IG.definition.grouping entries and associate the individual
# resource entries with the corresponding groupIds.
groups:
  LogicalModels:
    name: Logical Models
    description: Data Models representing the data structures and requirements for interoperability.
    resources:
      - StructureDefinition/PSSRequest
      - StructureDefinition/PSSResponse
      - StructureDefinition/PSSConsentModel
      - StructureDefinition/PSSFeedbackModel

  PlanDefinitions:
    name: PlanDefinitions (services)
    description: PlanDefinitions defining the service endpoints for using the PSS. These have the inputs and outputs represented by the profiles
    resources:
      - PlanDefinition/GetDiagnoses
      - PlanDefinition/GetDataToCollect
      - PlanDefinition/GetRecommendations

  Profiles: 
    name: Resource Profiles
    description: These define constraints on FHIR resources for systems conforming to this implementation guide
    resources:
      - StructureDefinition/PSSPatient
      - StructureDefinition/PSSRequestBundle
      - StructureDefinition/PSSResponseBundle
      - StructureDefinition/PSSDataAcquisitionForm
      - StructureDefinition/PSSResponseRequestGroup
      - StructureDefinition/PSSResponseMedicationRequest
      - StructureDefinition/PSSResponseServiceRequest
      - StructureDefinition/PSSResponseCommunicationRequest
      - StructureDefinition/PSSMedicationRequest
      - StructureDefinition/PSSQuestionnaireTask

  Extensions: 
    name: Extensions
    description: These define additional elements that can be exchanged with the respective FHIR resources
    resources:
      - StructureDefinition/CodeValueSet
      - StructureDefinition/PSSStructuredRating
      - StructureDefinition/PSSRelevantAge
      - StructureDefinition/AnswerOptionAdditionalCode
#      - StructureDefinition/PSSCodedRating


  Feedback:
    name: Feedback
    description: Feedback resources for the PSS services
    resources:
      - OperationDefinition/Feedback
      - Parameters/feedback-example


  Common-resources:
    name: Common examples
    description: Common examples - valid to multiple PSS services
    resources: 
      - Bundle/any-service-no-response-response
      # - RequestGroup/any-service-no-response-group
      - Bundle/any-service-no-consent-response-response
      - RequestGroup/26491cef-c5c7-4c5f-b10b-839e938f6b3c
      - Task/26491cef-c5c7-4c5f-b10b-839e938f6b3d
      - Questionnaire/26491cef-c5c7-4c5f-b10b-839e938f6b3e



  Antimicrobiology:
    name: Examples - Antimicrobiology
    description: Antimicrobiology PSS resource examples
    resources:
      - Patient/30551ce1-5a28-4356-b684-2e639094ad48
      - Bundle/getdatatocollect-a-data
      - Condition/30551ce1-5a28-4356-b684-2e639094ad01
      - AllergyIntolerance/30551ce1-5a28-4356-b684-2e639094ad02
      - MedicationRequest/30551ce1-5a28-4356-b684-2e639094ad12

      - Bundle/getdatatocollect-a-response
      - RequestGroup/getdatatocollect-a-response-group
      - Task/30551ce1-5a28-4356-b684-11ef43a67755
      - Questionnaire/30551ce1-5a28-4356-b684-2e639094ad4c
#      - ValueSet/condition-valueset
      - ValueSet/PregnancyCodes

      - Bundle/getrecommendations-a-data
      - QuestionnaireResponse/30551ce1-5a28-4356-b684-2e639094ac02

      - Bundle/getrecommendations-a-response
      - RequestGroup/getrecommendations-a-response-group
      - CommunicationRequest/30551ce1-5a28-4356-b684-1e639094dd22
      - MedicationRequest/30551ce1-5a28-4356-b684-1e639094ac23
      - MedicationRequest/30551ce1-5a28-4356-b684-1e639094ad24
      - MedicationRequest/30551ce1-5a28-4356-b684-1e639094ad26
      - MedicationRequest/30551ce1-5a28-4356-b684-1e639094ad29
      - QuestionnaireResponse/qr-consent-example

  Radiology:
    name: Examples - Radiology
    description: Radiology PSS resource examples
    resources: 
      - Patient/30551ce1-5a28-4356-b684-3e639094ad48
      - Bundle/radiology-getdiagnoses
      - Observation/ataxia
      - Bundle/radiology-getdiagnoses-response
      - RequestGroup/30551ce1-5a28-4356-b684-3e639094ad08
      - Task/1cdd5aab-1d4d-4965-bbe1-c851698d07f0
      - Condition/287e8fe2-3e83-44bd-92e7-962bc90b6d67
      - Task/db2698ba-cd0b-4c08-b57c-868ab5b95af6
      - Condition/5f3aafb8-643c-4ed5-ad54-199939e7b2d1
      - Task/30551ce1-5a28-4356-b684-3e639094ad11
      - Condition/30551ce1-5a28-4356-b684-4e639094ad11
      - Task/cfdfee5b-1db1-43fe-af72-4ea54b4e1a16
      - Condition/72d3ced6-5133-4042-931e-04284c9f4283
      - Task/54aad964-ad8a-4985-8ff1-3b09d707ee1e
      - Condition/b90ca57a-1ae5-4ff6-8dce-48488660ea65
      - Condition/pss-30551ce1-5a28-4356-b684-4e639094ad11      

      - Bundle/getrecommendations-data3
#      - Condition/proposed-diagnosis-head-trauma-v2
#      - ServiceRequest/ct-head-iv-contrast-v2

      - Bundle/getrecommendations-r-response
      - RequestGroup/getrecommendations-r-response-1
      - ServiceRequest/ct-head-wo-iv-contrast
      - ServiceRequest/pss-ct-head-wo-iv-contrast
      - ServiceRequest/30551ce1-5a28-4356-b684-1e639094ad23
      - ServiceRequest/30551ce1-5a28-4356-b684-1e639094ad22
      - ServiceRequest/30551ce1-5a28-4356-b684-1e639044ad77
#      - ServiceRequest/ct-head-with-or-without-contrast
#      - ServiceRequest/mr-head-without-contrast
      
#      - ServiceRequest/ct-head-iv-contrast


# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
pages:
  index.md:
    title: Home
  functional-overview.md:
    title: "Functional Overview"
  services.md:
    title: "Overview of PSS services"
    radiology.md:
      title: "Radiology"
    antimicrobiology.md:
      title: "Antimicrobiology"
  changes.xml:
  downloads.xml:
# The ImplementationGuide resource defines several other properties
# not represented above. These properties can be used as-is and
# should follow the format defined in ImplementationGuide:
# * meta
# * implicitRules
# * language
# * text
# * contained
# * extension
# * modifierExtension
# * experimental
# * useContext
# * copyright
# * packageId

# The menu property will be used to generate the input/menu.xml file.
# The menu is represented as a simple structure where the YAML key
# is the menu item name and the value is the URL. The IG publisher
# currently only supports one level deep on sub-menus.
# To provide a custom menu.xml file, do not include this property and
# include a `menu.xml` file in input/includes.
menu:
  Home: index.html
#  Guidance: guidance.html
  Artifacts: artifacts.html
  Downloads: downloads.html
  Changes: changes.html
#  History: ../history.html

# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array. For a
# partial list of allowed parameters see:
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters

#  excludettl: true
#  validation: [allow-any-extensions, no-broken-links]

# The FSHOnly flag indicates if only FSH resources should be exported.
# If set to true, no IG related content will be generated.
# The default value for this property is false.
FSHOnly: false

# When set to true, the "short" and "definition" field on the root element of an Extension will
# be set to the "Title" and "Description" of that Extension. Default is true.
#applyExtensionMetadataToRoot: false
parameters:
  pin-canonicals: pin-multiples
  auto-oid-root: 2.16.840.1.113883.2.51.22.2
  shownav: 'true'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'
#  path-expansion-params: ../../Parameters-terminology-expansion.json



