Instance: requireddataforantimicro-requestdata
InstanceOf: Parameters
Usage: #example
* parameter[0].name = "indication"
* parameter[=].valueCodeableConcept = $sct#921000172108 "Acute keelpijn"
* parameter[+].name = "intolerances"
* parameter[=].part[0].name = "intolerance"
* parameter[=].part[=].resource.resourceType = "AllergyIntolerance"
* parameter[=].part[=].resource.id = "allergy1"
* parameter[=].part[=].resource.meta.profile = "https://www.ehealth.fgov.be/standards/fhir/allergy/StructureDefinition/be-allergyintolerance"
* parameter[=].part[=].resource.clinicalStatus.coding.system = "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical"
* parameter[=].part[=].resource.clinicalStatus.coding.code = #"active"
* parameter[=].part[=].resource.verificationStatus.coding.system = "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification"
* parameter[=].part[=].resource.verificationStatus.coding.code = #"confirmed"
* parameter[=].part[=].resource.code.coding.system = "http://snomed.info/sct"
* parameter[=].part[=].resource.code.coding.code = #"91936005"
* parameter[=].part[=].resource.code.coding.display = "Allergy to penicillin"
* parameter[=].part[=].resource.patient.identifier.value = "Patient/dummy"
* parameter[=].part[=].resource.patient.identifier.system = "https://some.url"
* parameter[=].part[=].resource.recordedDate = "2024-07-08"
* parameter[=].part[=].resource.recorder.identifier.value = "12312312312"
* parameter[=].part[=].resource.recorder.identifier.system = "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/nihdi"
* parameter[=].part[+].name = "intolerance"
* parameter[=].part[=].resource.resourceType = "AllergyIntolerance"
* parameter[=].part[=].resource.id = "allergy2"
* parameter[=].part[=].resource.meta.profile = "https://www.ehealth.fgov.be/standards/fhir/allergy/StructureDefinition/be-allergyintolerance"
* parameter[=].part[=].resource.clinicalStatus.coding.system = "http://terminology.hl7.org/CodeSystem/allergyintolerance-clinical"
* parameter[=].part[=].resource.clinicalStatus.coding.code = #"active"
* parameter[=].part[=].resource.verificationStatus.coding.system = "http://terminology.hl7.org/CodeSystem/allergyintolerance-verification"
* parameter[=].part[=].resource.verificationStatus.coding.code = #"confirmed"
* parameter[=].part[=].resource.code.coding.system = "http://snomed.info/sct"
* parameter[=].part[=].resource.code.coding.code = #"282100009"
* parameter[=].part[=].resource.code.coding.display = "Adverse reaction to substance"
* parameter[=].part[=].resource.patient.identifier.value = "Patient/dummy"
* parameter[=].part[=].resource.patient.identifier.system = "https://some.url"
* parameter[=].part[=].resource.recordedDate = "2024-07-08"
* parameter[=].part[=].resource.recorder.identifier.value = "12312312312"
* parameter[=].part[=].resource.recorder.identifier.system = "https://www.ehealth.fgov.be/standards/fhir/core/NamingSystem/nihdi"
